# Generated by Django 5.2.14 on 2026-06-02 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=120, unique=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=180)),
                ('destinatario', models.CharField(max_length=20, unique=True)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo', models.BooleanField(default=True)),
                ('estado', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='envios.ruta')),
            ],
        ),
    ]
